images:
  daemon: docker.io/ceph/daemon:latest

labels:
  node_selector_key: ceph-storage
  node_selector_value: enabled

network:
  port:
    mon: 6789

storage:
  osd_directory: /var/lib/harbor/ceph/osd
  var_directory: /var/lib/harbor/ceph/ceph

# if you change provision_storage_class to false
# it is presumed you manage your own storage
# class definition externally
storageclass:
  provision_storage_class: true
  name: general
  monitors: ceph-mon.ceph:6789
  pool: rbd
  admin_id: admin
  admin_secret_name: pvc-ceph-conf-combined-storageclass
  admin_secret_namespace: nil
  user_id: admin
  user_secret_name: pvc-ceph-client-key
