---
apiVersion: v1
kind: Service
metadata:
  name: ceph-mon
  labels:
    app: ceph
    daemon: mon
spec:
  ports:
  - port: {{ .Values.network.port.mon }}
    protocol: TCP
    targetPort: {{ .Values.network.port.mon }}
  selector:
    app: ceph
    daemon: mon
  clusterIP: None
