---
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
    name: general
provisioner: kubernetes.io/rbd
parameters:
    monitors: ceph-mon.ceph:6789
    adminId: admin
    adminSecretName: pvc-ceph-conf-combined-storageclass
    adminSecretNamespace: ceph
    pool: rbd
    userId: admin
    userSecretName: pvc-ceph-client-key
